backend:
  name: git-gateway
  branch: main
collections: # A list of collections the CMS should be able to edit
  - name: 'recipe' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Recipe' # Used in the UI, ie.: "New Recipe"
    folder: 'src/pages/recipe' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Layout',          name: 'layout',         widget: 'hidden', default: '$/layouts/PostLayout.astro'}
      - { label: 'Date',            name: 'publishDate',    widget: 'date', format: 'yyyy-MM-dd' }
      - { label: 'Title',           name: 'title',          widget: 'string' }
      - { label: 'Description',     name: 'description',    widget: 'text' }
      - { label: 'Category',        name: 'category',       widget: 'string' }
      - { label: 'Key Ingredient',  name: 'keyIngredient',  widget: 'string' }
      - { label: 'Body',            name: 'body',           widget: 'markdown' }
